exclude: ["README.md", "how_to_blogpost.md"]

title : ClassRank
author :
  name : ClassRank
  github : github.com/classrank

url: "classrank.github.io"

markdown: rdiscount
permalink: pretty
highlighter: pygments
